### PR TITLE
first commit

### PR DESCRIPTION
**Pull request by raviikushh**
- Made lots of changes with UI for your future addition
- Added cards
- Removed Video bcoz it was not looking cool to the user POV
- I hope you like it
- review it and tell me if everything is good 
-

### CODE REVIEW

**Comment by raviikushh** [comment]
Can You please review my PR

**Comment by raviikushh** [comment]
- Added Dark Mode
- Can you please review my PR

**Comment by SagnikDeshmukh** [comment]
Provide the link of the website so that we maintainers could examine it . Once done I will merge it .

**Comment by raviikushh** [comment]
- This is the link https://raviikushh.github.io/MAKAUT_Organiser/ but I don't know why the dark theme is not working after hosting.
- Dark theme is working on my localhost
- I'm trying to figure out.

**Comment by raviikushh** [comment]
image
Screenshot (224)


- This is how it's looking

**Comment by raviikushh** [comment]
- I tried every possible way which seems to me to make it run, but it's not working please try something from your end and try to find out why it's not working.
- There is no "build" in the json file for the vite and also vite build is not runnig
- please try to merge and then see if it is working
- Or check what's wrong there beacuse "dark" class is also not working properly

**Comment by SagnikDeshmukh** [comment]
ok since you tried your best so for now i am merging it but make sure to improve it later

**Comment by raviikushh** [comment]
> ok since you tried your best so for now i am merging it but make sure to improve it later 

Sure.
Thank you 😊

**Pull request merged**
